### ISSUE TITLE
Does not start, any clue

### ISSUE THREAD

**Issue by Andries-Smit** [JelteMX/mx-modeler#1]
Does not start form the command line `mx-modeler` nor via `node`
Am i missing some (global) dependencies?

> C:\GitHub\mx-modeler> node.exe cli.js
> shell.js: internal error
> Error: Command failed: "C:\Program Files\nodejs\node.exe" C:\Users\Andries Smit\AppData\Local\Temp\shelljs_a3c01d4b03aef6819bcf
>     at checkExecSyncError (child_process.js:481:13)
>     at Object.execSync (child_process.js:521:13)
>     at execSync (C:\GitHub\mx-modeler\node_modules\shelljs\src\exec.js:81:11)
>     at Object._exec (C:\GitHub\mx-modeler\node_modules\shelljs\src\exec.js:214:12)
>     at Object.exec (C:\GitHub\mx-modeler\node_modules\shelljs\src\common.js:182:23)
>     at getShellOutput (C:\GitHub\mx-modeler\node_modules\node-mendix-modeler-path\index.js:10:21)
>     at findModeler (C:\GitHub\mx-modeler\node_modules\node-mendix-modeler-path\index.js:30:11)
>     at Object.<anonymous> (C:\GitHub\mx-modeler\node_modules\node-mendix-modeler-path\index.js:74:2)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)

**Comment by JelteMX** [comment]
Weird... It has something to do with ``shell.exec`` in a module that I wrote for Gulp/Grunt. Traces back to here: https://github.com/JelteMX/node-mendix-modeler-path/blob/master/index.js#L10

This is traced back to: https://github.com/JelteMX/node-mendix-modeler-path/blob/master/index.js#L30

I think I'll have to add a try...catch here

What system are you running this on? Windows 10? And what is the Node version? What happens if you run this command in a terminal: `assoc .mpr`?

**Comment by JelteMX** [comment]
Issues fixed in [1.4.0](https://github.com/JelteMX/mx-modeler/releases/tag/v1.4.0), closing issue
